caseConfig/force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This object holds a link between Case and Config object.</description>
    <label>Case Config</label>
    <nameField>
        <displayFormat>CCN-{00000}</displayFormat>
        <label>Case Config Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for a config</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the case for a particular config data.</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Configs</relationshipLabel>
    <relationshipName>Case_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label with config name</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of config</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

caseConfig/force-app/main/default/objects/Config__c/Config__c.object-meta.xml
<CustomObject>
    <description>This object hold record of all available configs</description>
    <label>Config</label>
    <nameField>
        <displayFormat>CN-{00000}</displayFormat>
        <label>Config Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount of config</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Field to save config name</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Config type</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

caseConfig/force-app/main/default/classes/CaseConfigController.cls
public with sharing class CaseConfigController {

    @AuraEnabled(cacheable=true)
    public static List<Config__c> getConfigData(String recordId){
        try {
            List<String> caseConfigLabels = new List<String>();
            for(Case_Config__c rec : [SELECT Label__c FROM Case_Config__c WHERE Case__c = :recordId LIMIT 50000]){
                caseConfigLabels.add(rec.Label__c);
            }
            return [
                SELECT Id, Label__c, Type__c, Amount__c
                FROM Config__c
                WHERE Label__c NOT IN :caseConfigLabels
                LIMIT 50000];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Case_Config__c> getCaseConfigData(String recordId){
        try {
            return [SELECT Id, Label__c, Type__c, Amount__c, Case__r.Status FROM Case_Config__c WHERE Case__c = :recordId LIMIT 50000];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<Case_Config__c> addConfigData(String recordId, List<Config__c> newConfigRecs){
        try {
            List<Case_Config__c> newCaseConfigRecs = new List<Case_Config__c>();
            Case_Config__c caseConfigObj;
            for(Config__c rec : newConfigRecs){
                caseConfigObj = new Case_Config__c();
                caseConfigObj.Label__c = rec.Label__c;
                caseConfigObj.Type__c = rec.Type__c;
                caseConfigObj.Amount__c = rec.Amount__c;
                caseConfigObj.Case__c = recordId;
                newCaseConfigRecs.add(caseConfigObj);
            }
            if(!newCaseConfigRecs.isEmpty()){
                Database.insert(newCaseConfigRecs);
            }
            return newCaseConfigRecs;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}