caseConfig/force-app/main/default/objects/Case_Config__c/Case_Config__c.object-meta.xml
<CustomObject>
    <description>This object holds a link between Case and Config object.</description>
    <label>Case Config</label>
    <nameField>
        <displayFormat>CCN-{00000}</displayFormat>
        <label>Case Config Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Amount for a config</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>Label with config name</description>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

caseConfig/force-app/main/default/objects/Case_Config__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of config</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

caseConfig/force-app/main/default/classes/CaseDataRequest.cls
public with sharing class CaseDataRequest {
    public CaseDataRequest(String caseRecId){
        Case caseData = [SELECT Id, Status, (SELECT Id, Label__c, Type__c, Amount__c FROM Case_Configs__r) FROM Case WHERE Id = :caseRecId LIMIT 1];
        if(caseData != null){
            System.debug(JSON.serialize(caseData));
            caseId = caseData.Id;
            status = 'Closed';
            CaseConfigRequest caseConfigRequestObj;
            for(Case_Config__c rec : caseData.Case_Configs__r){
                caseConfigRequestObj = new CaseConfigRequest();
                caseConfigRequestObj.label = rec.Label__c;
                caseConfigRequestObj.type = rec.Type__c;
                caseConfigRequestObj.amount = rec.Amount__c;
                caseConfigs.add(caseConfigRequestObj);
            }
        }
    }
    public string caseId;
    public string status;
    public List<CaseConfigRequest> caseConfigs = new List<CaseConfigRequest>();

    class CaseConfigRequest{
        String label;
        String type;
        Decimal amount;
    }
}